---
- name: Install hdparm.
  package: name=hdparm state=present
  tags: [ 'package', 'hdparm' ]

- name: Generate hdparm.conf file
  template:
    src: hdparm.conf.j2
    dest: /etc/hdparm.conf
  when: hdparm_manage_config
  tags: [ 'configuration', 'hdparm' ]
